site_name: Recipes and Cocktails
site_url: http://chris-m92.github.io/recipes-and-cocktails
nav:
  - Home:
    - index.md
  - Cocktails:
    - 'cocktails/cocktails.md'
    - 'cocktails/aquavit.md'
    - 'cocktails/batches.md'
    - 'cocktails/bourbon.md'
    - 'cocktails/brandy.md'
    - 'cocktails/cachaca.md'
    - 'cocktails/champagne.md'
    - 'cocktails/cognac.md'
    - 'cocktails/cordials.md'
    - 'cocktails/daiquiris.md'
    - 'cocktails/fizzes.md'
    - 'cocktails/flavor-buddies.md'
    - 'cocktails/flips.md'
    - 'cocktails/fortified-wine.md'
    - 'cocktails/gin.md'
    - 'cocktails/honey-liqueur.md'
    - 'cocktails/infusions.md'
    - 'cocktails/irish-whiskey.md'
    - 'cocktails/japanese-whisky.md'
    - 'cocktails/juleps.md'
    - 'cocktails/manhattan-variations.md'
    - 'cocktails/miscellany.md'
    - 'cocktails/multiple-choice.md'
    - 'cocktails/negroni-variations.md'
    - 'cocktails/old-fashioned-variations.md'
    - 'cocktails/pisco.md'
    - 'cocktails/punch.md'
    - 'cocktails/rims.md'
    - 'cocktails/rum.md'
    - 'cocktails/rye.md'
    - 'cocktails/sazerac-variations.md'
    - 'cocktails/scotch.md'
    - 'cocktails/sherry.md'
    - 'cocktails/st-germain.md'
    - 'cocktails/swizzles.md'
    - 'cocktails/syrups.md'
    - 'cocktails/tea.md'
    - 'cocktails/tequila.md'
    - 'cocktails/tikis.md'
    - 'cocktails/vodka.md'
    - 'cocktails/whiskey.md'
  - Receipes:
    - 'recipes/recipes.md'
    - Desserts:
      - 'recipes/desserts/buttermilk-pecan-pie.md'
    - Entrees:
      - Beef:
        - 'recipes/entrees/beef/air-fryer-beef-bulgogi-burgers.md'
        - 'recipes/entrees/beef/strawberry-steak-salad.md'
      - Chicken:
        - 'recipes/entrees/chicken/chicken-cobb-salad.md'
        - 'recipes/entrees/chicken/chicken-meatball-and-hummus-tabbouleh-bowl.md'
        - 'recipes/entrees/chicken/chicken-mole.md'
        - 'recipes/entrees/chicken/chicken-schwarma-salad.md'
        - 'recipes/entrees/chicken/chicken-spinach-artichoke-rice-casserole.md'
        - 'recipes/entrees/chicken/instant-pot-butter-chicken.md'
        - 'recipes/entrees/chicken/instant-pot-indian-chicken-curry.md'
        - 'recipes/entrees/chicken/mamaws-chicken-and-rice-casserole.md'
      - Lamb:
        - 'recipes/entrees/lamb/garlic-crusted-roast-rack-of-lamb.md'
        - 'recipes/entrees/lamb/lamb-rogan-josh.md'
      - Pork:
        - 'recipes/entrees/pork/grilled-pork-tenderloin-charred-chile-adobo.md'
        - 'recipes/entrees/pork/pork-and-spinach-saag.md'
        - 'recipes/entrees/pork/pressure-cooker-dae-ji-bulgogi-korean-spicy-pork.md'
        - 'recipes/entrees/pork/slow-cooker-tacos-al-pastor.md'
        - 'recipes/entrees/pork/spicy-sausage-ragu.md'
      - Turkey:
        - 'recipes/entrees/turkey/curried-turkey-hotpot.md'  
      - Vegetarian:
        - 'recipes/entrees/vegetarian/baingan-bharta.md'
        - 'recipes/entrees/vegetarian/butternut-squash-soup.md'
        - 'recipes/entrees/vegetarian/chickpea-and-coconut-curry.md'
        - 'recipes/entrees/vegetarian/ravioli-with-sage-brown-butter-sauce-spinach-and-walnuts.md'
    - Sauces:
      - 'recipes/sauces/gordon-ramsey-lamb-stock.md'    
    - Sides:
      - Dairy:
        - 'recipes/sides/dairy/paneer.md'
      - Starch:
        - 'recipes/sides/starch/cheddar-and-spinach-twice-baked-potatoes.md'
        - 'recipes/sides/starch/texas-garlic-mashed-potatoes.md'
      - Vegetables:
        - 'recipes/sides/vegetables/bacon-jam-brussels-sprouts.md'
        - 'recipes/sides/vegetables/easy-palak-paneer.md'
        - 'recipes/sides/vegetables/palak-paneer.md'
theme:
  name: 'material'
  favicon: 'img/favicon.ico'
  icon:
    logo: material/glass-cocktail
  features:
    - tabs
    - instant
markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - footnotes
  - pymdownx.tilde
  - pymdownx.details
  - pymdownx.keys
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.highlight:
      use_pygments: true
      linenums: true
extra_css:
  - stylesheets/styles.css